### PR TITLE
Fix(core): Fixed Popover target extra "div" wrapper

### LINKED ISSUE #129: Bug: Popover target has extra "div" wrapper
This seems weird. In the source code, the div with custom style is the direct parent of the button. In the rendered HTML, there are 2 other divs in-between. This sounds wrong. There should only be 1 div in the middle (the one of TargetWrapper)

image

### PR DESCRIPTION
**Pull request by monodyle**
Fixed #129

### CODE REVIEW

File: core/src/popover/popover.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const Popover = (props: PopoverProps) => {
 	const TargetWrapper = props.TargetWrapper ?? DefaultTargetWrapper;
 
 	return (
-		<div>
+		<Fragment>
```
Comment (thien-do) [inline core/src/popover/popover.tsx:56]: Why the fuck did I use <div> instead of <Fragment>

**Review by thien-do — APPROVED** [review]
