### PR TITLE
Fix(core): Fix custom props of Input

### LINKED ISSUE #244: Warning when using setValue prop of Input component
`setValue` is accidentally passed as raw property into native <input/> component in Moai Input component. 
It caused the warning by React:
Screen Shot 2021-06-30 at 15 30 53

I take a look in the code, and recognize that the root cause maybe due to these lines:
https://github.com/moaijs/moai/blob/a384b2cd78661e598e69826b658d8dea4e32156f/lib/core/src/input/input.tsx#L126
https://github.com/moaijs/moai/blob/a384b2cd78661e598e69826b658d8dea4e32156f/lib/core/src/input/input.tsx#L131

### PR DESCRIPTION
**Pull request by lqt93**
Resolve #244

### CODE REVIEW

File: lib/core/src/input/input.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ const inputRender = (
 ): JSX.Element => {
 	validate(props);
 	const size = props.size ?? Input.sizes.medium;
-	const rawProps = omit(props, ["size", "style"]);
+	const rawProps = omit(props, ["size", "style", "setValue", "icon", "list"]);
```
Comment (thien-do) [inline lib/core/src/input/input.tsx:126]: Can you also exclude "onChange" and "value" too? We already override them below, but I think it's better to explicitly exclude them here

Comment (lqt93) [reply lib/core/src/input/input.tsx]: yeah, done 🥳

**Review by thien-do — APPROVED** [review]
